site_name: START Documentation
site_url: https://activeinferenceinstitute.github.io/Start/
repo_url: https://github.com/ActiveInferenceInstitute/Start
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Environment: environment.md
  - Pipeline: pipeline.md
  - Configuration: configuration.md
  - Testing: TESTING.md
  - Examples: examples.md
  - Clone Management: clones.md
  - Conventions: conventions.md
  - Other:
      - Overview: other/index.md
      - Inferant Stream 015-1: other/inferant_stream_015-1.md
  - Learning Guides:
      - Usage Guide: https://github.com/ActiveInferenceInstitute/Start/blob/main/learning/curriculum_creation/USAGE_GUIDE.md
      - API Integration: https://github.com/ActiveInferenceInstitute/Start/blob/main/learning/curriculum_creation/README.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - tables
  - def_list
  - footnotes
  - attr_list
